In [61]:
import pandas as pd
from matplotlib import pyplot as plt
import seaborn as sns

pd.set_option('display.max_columns', None)

In [62]:
df_survey = pd.read_csv('../datasets/survey_data_transformed.csv')
df_survey.head()

,Age,Sleep Duration,CGPA,Work/Study Hours,Academic/Work Pressure,Study/Job Satisfaction,Financial Stress,Dietary Habits,Physical Activity Frequency,Social Media Usage Hours,Body Image Satisfaction,Loneliness Frequency,Depression,Age_Group,Gender_Male,Working Professional or Student_Working Professional,Suicidal Thoughts_Yes,Family Mental Illness History_Yes,Study Degree_Engineering Diploma,Study Degree_High School,Study Degree_Masterâ€™s Degree,Study Degree_PhD,Study Degree_Preparatory Classes,Marital Status_Single,Religious Person_yes,Living with Family_yes,Living Environment Satisfaction_yes,Night/Day Sleep Preference_During the day,Smoking_yes,Alcohol Consumption_yes,Self-Comparison_Yes,Profession_Craftsman,Profession_Decorator,Profession_E-commerce,Profession_Student,Profession_Unknown,Profession_Warehouse Worker
0,20,3,7.0,11,4,4,3,1,2,3,5,1,0,1,1,0,0,1,0,0,1,0,0,1,1,0,1,0,0,0,0,0,0,0,1,0,0
1,23,0,8.0,5,3,4,4,0,1,0,2,2,0,2,1,0,0,0,0,0,0,0,0,1,1,0,1,0,0,0,1,0,0,0,1,0,0
2,22,0,7.0,3,3,2,4,1,2,0,4,1,0,1,1,1,0,0,0,0,0,1,0,1,1,1,0,0,1,0,0,0,0,0,0,1,0
3,18,0,7.0,6,3,4,1,1,0,1,3,2,0,0,1,1,0,1,0,1,0,0,0,1,1,1,0,0,0,0,1,0,0,1,0,0,0
4,17,2,6.0,6,2,2,4,2,0,0,4,2,0,0,1,0,0,0,0,1,0,0,0,1,1,1,0,0,0,0,0,0,0,0,1,0,0

In [63]:
df_kaggle = pd.read_csv('../datasets/kaggle_data_transfromed.csv')
df_kaggle.head()

,Age,Sleep Duration,Work/Study Hours,Financial Stress,Dietary Habits,Depression,Academic/Work Pressure,Study/Job Satisfaction,Age_Group,Gender_Male,Working Professional or Student_Working Professional,Suicidal Thoughts_Yes,Family Mental Illness History_Yes,Study Degree_High School,Study Degree_Masterâ€™s Degree,Study Degree_PhD,Study Degree_Unknown,Profession_Architect,Profession_Business Analyst,Profession_Chef,Profession_Chemist,Profession_Civil Engineer,Profession_Consultant,Profession_Content Writer,Profession_Customer Support,Profession_Data Scientist,Profession_Digital Marketer,Profession_Doctor,Profession_Educational Consultant,Profession_Electrician,Profession_Entrepreneur,Profession_Financial Analyst,Profession_Graphic Designer,Profession_HR Manager,Profession_Investment Banker,Profession_Judge,Profession_Lawyer,Profession_Manager,Profession_Marketing Manager,Profession_Mechanical Engineer,Profession_Pharmacist,Profession_Pilot,Profession_Plumber,Profession_Research Analyst,Profession_Researcher,Profession_Sales Executive,Profession_Software Engineer,Profession_Student,Profession_Teacher,Profession_Travel Consultant,Profession_UX/UI Designer,Profession_Unknown
0,49.0,3,1.0,2,0,0,5,2,10,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1,26.0,2,7.0,3,2,1,4,3,3,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
2,33.0,0,3.0,1,0,1,5,2,5,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0
3,22.0,2,10.0,1,1,1,5,1,1,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
4,30.0,0,9.0,4,2,0,1,1,4,0,1,1,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [64]:
df_empty = pd.DataFrame(columns=df_kaggle.columns)

In [65]:
columns_empty = df_empty.columns
for column in columns_empty:
    if column in df_survey.columns:
        df_empty[column] = df_survey[column]
    
df_empty.head()

,Age,Sleep Duration,Work/Study Hours,Financial Stress,Dietary Habits,Depression,Academic/Work Pressure,Study/Job Satisfaction,Age_Group,Gender_Male,Working Professional or Student_Working Professional,Suicidal Thoughts_Yes,Family Mental Illness History_Yes,Study Degree_High School,Study Degree_Masterâ€™s Degree,Study Degree_PhD,Study Degree_Unknown,Profession_Architect,Profession_Business Analyst,Profession_Chef,Profession_Chemist,Profession_Civil Engineer,Profession_Consultant,Profession_Content Writer,Profession_Customer Support,Profession_Data Scientist,Profession_Digital Marketer,Profession_Doctor,Profession_Educational Consultant,Profession_Electrician,Profession_Entrepreneur,Profession_Financial Analyst,Profession_Graphic Designer,Profession_HR Manager,Profession_Investment Banker,Profession_Judge,Profession_Lawyer,Profession_Manager,Profession_Marketing Manager,Profession_Mechanical Engineer,Profession_Pharmacist,Profession_Pilot,Profession_Plumber,Profession_Research Analyst,Profession_Researcher,Profession_Sales Executive,Profession_Software Engineer,Profession_Student,Profession_Teacher,Profession_Travel Consultant,Profession_UX/UI Designer,Profession_Unknown
0,20,3,11,3,1,0,4,4,1,1,0,0,1,0,1,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,0
1,23,0,5,4,0,0,3,4,2,1,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,0
2,22,0,3,4,1,0,3,2,1,1,1,0,0,0,0,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,1
3,18,0,6,1,1,0,3,4,0,1,1,0,1,1,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,0
4,17,2,6,4,2,0,2,2,0,1,0,0,0,1,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,0

In [67]:
# Define the logic to fill the 'Study Degree_Unknown' column
def fill_study_degree_unknown(row):
    if row['Study Degree_High School'] == 0 and row['Study Degree_Masterâ€™s Degree'] == 0 and row['Study Degree_PhD'] == 0:
        return 1
    else:
        return 0

# Apply the function to each row in the df_empty dataframe
df_empty['Study Degree_Unknown'] = df_empty.apply(fill_study_degree_unknown, axis=1)
df_empty.head()

,Age,Sleep Duration,Work/Study Hours,Financial Stress,Dietary Habits,Depression,Academic/Work Pressure,Study/Job Satisfaction,Age_Group,Gender_Male,Working Professional or Student_Working Professional,Suicidal Thoughts_Yes,Family Mental Illness History_Yes,Study Degree_High School,Study Degree_Masterâ€™s Degree,Study Degree_PhD,Study Degree_Unknown,Profession_Architect,Profession_Business Analyst,Profession_Chef,Profession_Chemist,Profession_Civil Engineer,Profession_Consultant,Profession_Content Writer,Profession_Customer Support,Profession_Data Scientist,Profession_Digital Marketer,Profession_Doctor,Profession_Educational Consultant,Profession_Electrician,Profession_Entrepreneur,Profession_Financial Analyst,Profession_Graphic Designer,Profession_HR Manager,Profession_Investment Banker,Profession_Judge,Profession_Lawyer,Profession_Manager,Profession_Marketing Manager,Profession_Mechanical Engineer,Profession_Pharmacist,Profession_Pilot,Profession_Plumber,Profession_Research Analyst,Profession_Researcher,Profession_Sales Executive,Profession_Software Engineer,Profession_Student,Profession_Teacher,Profession_Travel Consultant,Profession_UX/UI Designer,Profession_Unknown
0,20,3,11,3,1,0,4,4,1,1,0,0,1,0,1,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,0
1,23,0,5,4,0,0,3,4,2,1,0,0,0,0,0,0,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,0
2,22,0,3,4,1,0,3,2,1,1,1,0,0,0,0,1,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,1
3,18,0,6,1,1,0,3,4,0,1,1,0,1,1,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,0
4,17,2,6,4,2,0,2,2,0,1,0,0,0,1,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,0

In [72]:
import numpy as np
import random


profession_columns = [col for col in df_empty.columns if col.startswith('Profession')]
# Iterate over each row in the dataframe
for index, row in df_empty.iterrows():
    # Check if 'Profession_Student' or 'Profession_Unknown' are 1
    if row['Profession_Student'] == 1 or row['Profession_Unknown'] == 1:
        # If either is 1, set all other profession columns to 0
        for col in profession_columns:
            df_empty.at[index, col] = 0
    else:
        # If both are 0, randomly set one profession column (other than 'Profession_Student' and 'Profession_Unknown') to 1
        random_profession = random.choice(profession_columns)
        for col in profession_columns:
            if col == random_profession:
                df_empty.at[index, col] = 1
            else:
                df_empty.at[index, col] = 0
df_empty.head()

,Age,Sleep Duration,Work/Study Hours,Financial Stress,Dietary Habits,Depression,Academic/Work Pressure,Study/Job Satisfaction,Age_Group,Gender_Male,Working Professional or Student_Working Professional,Suicidal Thoughts_Yes,Family Mental Illness History_Yes,Study Degree_High School,Study Degree_Masterâ€™s Degree,Study Degree_PhD,Study Degree_Unknown,Profession_Architect,Profession_Business Analyst,Profession_Chef,Profession_Chemist,Profession_Civil Engineer,Profession_Consultant,Profession_Content Writer,Profession_Customer Support,Profession_Data Scientist,Profession_Digital Marketer,Profession_Doctor,Profession_Educational Consultant,Profession_Electrician,Profession_Entrepreneur,Profession_Financial Analyst,Profession_Graphic Designer,Profession_HR Manager,Profession_Investment Banker,Profession_Judge,Profession_Lawyer,Profession_Manager,Profession_Marketing Manager,Profession_Mechanical Engineer,Profession_Pharmacist,Profession_Pilot,Profession_Plumber,Profession_Research Analyst,Profession_Researcher,Profession_Sales Executive,Profession_Software Engineer,Profession_Student,Profession_Teacher,Profession_Travel Consultant,Profession_UX/UI Designer,Profession_Unknown
0,20,3,11,3,1,0,4,4,1,1,0,0,1,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1,23,0,5,4,0,0,3,4,2,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
2,22,0,3,4,1,0,3,2,1,1,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0
3,18,0,6,1,1,0,3,4,0,1,1,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4,17,2,6,4,2,0,2,2,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0

# CatBoost Fine Tuning

In [75]:
import pandas as pd
from catboost import CatBoostClassifier

# Load the pre-trained model
model = CatBoostClassifier()
model.load_model("catboost_model.cbm")

# Fine-tune the model on the survey dataset
model.fit(X, y,verbose=0)

# Save the fine-tuned model
model.save_model("catboost_model_fine_tuned.cbm")

print("Model fine-tuned and saved as 'catboost_model_fine_tuned.cbm'.")

Model fine-tuned and saved as 'catboost_model_fine_tuned.cbm'.